### ISSUE TITLE
WEで選択しているのに0ブロック判定になってしまう

### ISSUE THREAD

**Issue by yuuahp** [jaoafa/Light#1]
![image](https://user-images.githubusercontent.com/53546237/119138769-3488f000-ba7d-11eb-8a17-1a5d2c82c4b2.png)

WE選択してからAddlightしても選択範囲が0ブロックの判定になります

**Comment by book000** [comment]
v1.1 (https://github.com/jaoafa/Light/releases/tag/v1.1) で修正済みだったのですが本番環境に反映し忘れていました…

**Comment by yuuahp** [comment]
了解です
